version: '3.9'

services:

  app:
    image: kangstek/manajemen-ujian-laravel:alpha-0.2.16
    
    container_name: manajemen-ujian-laravel-app-dev

    working_dir: /var/www

    env_file:
      - ./docker/app/.env.dev

    volumes:
      - app-data:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    
    networks:
      - manajemen-ujian-laravel-net

  webserver:
    image: nginx:1.25.3
    container_name: manajemen-ujian-laravel-webserver-dev

    ports:
      - 8001:80

    volumes:
      - app-data:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - manajemen-ujian-laravel-net
  
  db:
    image: mariadb:10.7.8
    container_name: manajemen-ujian-laravel-db-dev

    ports:
      - 3001:3306
    
    environment:
      MARIADB_ROOT_PASSWORD: 'toor'
      MARIADB_DATABASE: 'manajemen-ujian-db'
      MARIADB_USER: 'lara'
      MARIADB_PASSWORD: 'lara'
    
    volumes:
      - manajemen-ujian-laravel-data:/var/lib/mysql
    
    networks:
      - manajemen-ujian-laravel-net
  
  cache:
    image: redis:6.2-alpine
    container_name: manajemen-ujian-laravel-cache-dev
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass XSuUzaai3ba/b17MIE9o97Z8ModP3YX6VCtt2TG2OEQHcoBhnvs7vZu+qE97SL259jM044zxUJKe2o8Hwww@694225724d66
    volumes:
      - manajemen-ujian-laravel-cache:/data
    networks:
      - manajemen-ujian-laravel-net
    

volumes:
  app-data:
    driver: local
  manajemen-ujian-laravel-data:
    driver: local
  manajemen-ujian-laravel-cache:
    driver: local


networks:
  manajemen-ujian-laravel-net:
    driver: bridge