version: '3.9'

services:

  app:
    image: kangstek/manajemen-ujian-laravel:alpha-0.2.13
    
    container_name: manajemen-ujian-laravel-app-prod

    working_dir: /var/www

    env_file:
      - ./docker/app/.env.prod

    volumes:
      - app-data:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    
    networks:
      - manajemen-ujian-laravel-net

  webserver:
    image: nginx:1.25.3
    container_name: manajemen-ujian-laravel-webserver-prod

    ports:
      - 8001:80
      - 443:443

    volumes:
      - app-data:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl/cert.pem:/etc/ssl/atapnegeri.pem
      - ./docker/nginx/ssl/key.key:/etc/ssl/atapnegeri.key
      - ./docker/nginx/ssl/cloudflare.crt:/etc/ssl/cloudflare.crt

    networks:
      - manajemen-ujian-laravel-net
  
  cache:
    image: redis:6.2-alpine
    container_name: manajemen-ujian-laravel-cache-prod
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass XSuUzaai3ba/b17MIE9o97Z8ModP3YX6VCtt2TG2OEQHcoBhnvs7vZu+qE97SL259jM044zxUJKe2o8Hwww@694225724d66
    volumes:
      - manajemen-ujian-laravel-cache:/data
    networks:
      - manajemen-ujian-laravel-net
    

volumes:
  app-data:
    driver: local
  manajemen-ujian-laravel-cache:
    driver: local


networks:
  manajemen-ujian-laravel-net:
    driver: bridge